### ISSUE TITLE
Flex like features?

### ISSUE THREAD

**Issue by sigstop** [zaach/jison#171]
I apologize for posting this here, but I could not find an active Jison discussion group.   Feel free to redirect me to the same.  Fair warning: I am somewhat of a newbie to JavaScript.  

After looking at the Jison documentation, and examples, it was not obvious to me how to write a simple flex program like the one below found in O'Reilly book "Flex and Bison" in Jison.    It was clear that something more complex than the below can be written in Jison to accomplish the same thing.  

Is it possible to declare and access "global" variables in the lex portion of a Jison file?  Any held would be appreciated.

/\* just like Unix wc */
%{
int chars = 0;
int words = 0;
int lines = 0;
%}

%%

[^ \t\n\r\f\v]+  { words++; chars += strlen(yytext); }
\n     { chars++; lines++; }
.      { chars++; }

%%

main(int argc, char **argv)
{
 yylex();
 printf("%8d%8d%8d\n", lines, words, chars);
}

**Comment by haskellcamargo** [comment]
@zaach, in the latest version of Jison, your example is not valid. On parser context, it will generate an error saying that `chars` is not defined.
