### ISSUE TITLE
Use Regex Modifiers

### ISSUE THREAD

**Issue by edi9999** [zaach/jison#229]
Is they a way to write the regex you write in `lex.rules` with modifiers, eg 

           ["CLASS","return 'CLASS';"]

to be case insensitive, eg match "class, Class, ClAss, ..." ?

**Comment by edi9999** [comment]
up @zaach any idea ?

**Comment by zaach** [comment]
Try using a regex instead of a string, e.g. `[/CLASS/i, "return 'CLASS'"]`

**Comment by edi9999** [comment]
Seems to work, thanks !
