### ISSUE TITLE
Multiple start productions

### ISSUE THREAD

**Issue by thelonious** [zaach/jison#242]
Is there a way to have parsing begin at arbitrary productions within a grammar? As one example, I have an expression grammar that I would like to repurpose for different parsing situations. In one case, I would like to begin parsing at a top-level 'expression' production. In other cases, I would like parsing to begin at a lower-level 'boolean-expression'. The only options I see are to a) define separate grammars or b) somehow make the grammar JSONs composable, but it would be great if I could indicate the starting production when I invoke 'parse'.

**Comment by JMPSequeira** [comment]
a little late for the party 🥇 

```jison
%lex

%%

\s+                   /* skip whitespace */
"FUNCTION"              return 'FUNCTION';
"EXPRESSION"            return 'EXPRESSION';
<<EOF>>                 return 'EOF';

/lex

%token FUNC
%token EXPR

%start schema

%%

schema
    : expression EOF
    | functionDeclaration EOF
    ;
expression
    : EXPR EXPRESSION
    ;
    
functionDeclaration
    : FUNC FUNCTION
    ;
```


```javascript
function parse(input, mode) {
  const parser = new jison.Parser(fs.readFileSync("test.jison", "utf8")),
    lexerProto = parser.lexer,
    lexerProtoLex = lexerProto.lex;

  let modeSet = false;

  lexerProto.lex = function () {
    if (modeSet) {
      this.lex = lexerProtoLex;
      return this.lex();
    }

    return (modeSet = parser.__proto__.symbols_[mode]);
  };

  return parser.parse(input);
}

parse("FUNCTION", "FUNC");
```

hope it helps anyone
