### ISSUE TITLE
Jison no longer produces strict output

### ISSUE THREAD

**Issue by bramp** [zaach/jison#285]
Since d1d8ae99d34bf1ef389a0653714fb0b652cca903 jison has been producing code that contains:
```javascript
    function popStack(n) {
        stack.length = stack.length - 2 * n;
        vstack.length = vstack.length - n;
        lstack.length = lstack.length - n;
    }
    _token_stack:
        function lex() {
            var token;
            token = lexer.lex() || EOF;
            if (typeof token !== 'number') {
                token = self.symbols_[token] || token;
            }
            return token;
        }
```

I include the generated jison code within a "use strict" block. When loading this file with nodejs, I get the following error:
```
/Users/bramp/personal/js-sequence-diagrams/build/sequence-diagram.js:271
        function lex() {
        ^^^^^^^^
SyntaxError: In strict mode code, functions can only be declared at top level or immediately within another function.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

If I remove the "_token_stack:" label, the error disappears. Additionally, it seems the _token_stack label is not actually used in my generated file, so I'm unsure if it's safe to delete.

**Comment by Alxandr** [comment]
This is causing some rather annoying results, as it (for instance) does not allow me to use some ES6 code in io.js given that it requires strict mode.

**Comment by mbektimirov** [comment]
Any progress on this issue? For now it is impossible to use generated parser with Babel in strict mode. Blacklisting strict mode is not preferable solution here.

**Comment by hannupekka** [comment]
Also having this with browserify.

**Comment by GerHobbelt** [comment]
For the ones who need this badly: https://github.com/GerHobbelt/jison
though be warned: I fixed that by kicking out Esprima and replacing that with a few extra labels and regex-based code block removals

 (jison used Esprima to tweak the core of the generated parsers, but it effed up the core and action code comments which help me to diag/debug grammars in the wild :-1: -- another @GerHobbelt feature where the grammar rule gets printed as a comment with the `$$...` action code in the output; handy when you're debugging through the bugger)

**Comment by blake-regalia** [comment]
+1

**Comment by somethingnew2-0** [comment]
Confirmed https://github.com/zaach/jison/commit/b9d567317aa91bb1b6462bef5671623216673711 fixes it.  @zaach could you push a release to npm?

**Comment by zaach** [comment]
Aye, 0.4.16 has been published. Thanks y'all!
