### ISSUE TITLE
Html parsing

### ISSUE THREAD

**Issue by elfet** [zaach/jison#306]
Is it possible to oarse html with jison?

**Comment by Alxandr** [comment]
html, with all it's quirks, as far as I know isn't a context free grammar (I might be wrong). There are certain tags in which things behave differently for instance (like `<script>` and `<style>`), and some tags self-close, while others doesn't even allow short-form.

I reccomend https://github.com/fb55/htmlparser2.

**Comment by elfet** [comment]
Yes, i'm already using htmlparser2, but i really want to create my own grammar for parsing html (or maybe some simple subset on html).

**Comment by yosbelms** [comment]
@elfet, yes you can

**Comment by elfet** [comment]
Great! Will try to implement it. 
Can any body send me a link of example grammar for parsing html?

**Comment by yosbelms** [comment]
@elfet, I made it for you using @nolanlawson 's jison debugger (http://nolanlawson.github.io/jison-debugger/).

The grammar itself is not sophisticated but I it is a good starting point

```
   %lex
   %%
   \s+                           /* skip whitespace */
   "<"                           return "<"
   ">"                           return ">"
   "/"                           return "/"
   "="                           return "="
   \"[a-zA-Z]+\"                 return "STRING"
   [a-zA-Z0-9]+                  return "IDENT"
   <<EOF>>                       return "EOF"
   .                             return "INVALID"
   /lex

   %ebnf
   %start Document
   %%
   Document
     : ElementList EOF
     ;

   ElementList
     : Element
     | ElementList Element
     ;

   Element
     : "<" IDENT AttrList "/" ">"
     | "<" IDENT AttrList ">" "<" "/" IDENT ">"
     | "<" IDENT AttrList ">" ElementList  "<" "/" IDENT ">"
     ;

   AttrList
     : Attr
     | AttrList Attr
     |
     ;

   Attr
     : IDENT "=" STRING
     ;
```

should parse

```xml
   <link src="zzz" />
   <div class="asdasd" hidden="true">
      <div class="internal"></div>
   </div>
```

**Comment by elfet** [comment]
Thanks a lot!

**Comment by elfet** [comment]
@yosbelms one more question about this production:
```
| "<" IDENT AttrList ">" ElementList  "<" "/" IDENT ">"
```
Now it will parse some errors like this:
```
<div class="asdasd" hidden="true">
    <div class="internal"></div>
</divnot>
```

How to check in grammar what $2 IDENT equals $8 IDENT?

Thanks!

**Comment by elfet** [comment]
Found solution:
```
        {
            if ($2 == $8) {
                $$ = new ElementNode($2, $3, $5, createSourceLocation(null, @1, @2));
            } else {
                throw new SyntaxError('Not equals!');
            }
        }
```

**Comment by yosbelms** [comment]
@elfet, there is a github repository for this project?

**Comment by elfet** [comment]
I am creating [JavaScript template engine](https://github.com/monkberry/monkberry) which will compile from HTML to DOM.

**Comment by elfet** [comment]
And here is my grammar: https://github.com/monkberry/monkberry/blob/master/parser/grammar.jison
