### ISSUE TITLE
Any chance for a new release (0.4.16)?

### ISSUE THREAD

**Issue by schmich** [zaach/jison#307]
The last public release was 0.4.15 [over a year ago](https://github.com/zaach/jison/commit/3821a184db715b50c3f56bf2f04061fed520987c). There have been a number of fixes that would be good to see in a new release (specifically, [this fix](https://github.com/zaach/jison/commit/7bcf8b7ed7337939b31a207881eba1c61ae47018)).

Could we get a 0.4.16 release that rolls up these fixes?

**Comment by dshook** [comment]
+1 on that

**Comment by yosbelms** [comment]
+1

**Comment by zaach** [comment]
0.4.17 is out

**Comment by yosbelms** [comment]
What's new?

**Comment by techtonik** [comment]
@yosbelms there are no tags in repository, but see https://github.com/zaach/jison/commits/master
