### ISSUE TITLE
How to generate case-insensitive lexer from command line?

### ISSUE THREAD

**Issue by vjeux** [zaach/jison#82]
I can see that there's an [option to handle case-sensitiveness](https://github.com/zaach/jison/blob/master/lib/jison/lexer.js#L47) in the lexer but is there a way to enable it from the `jison` executable?

I'm looking for something like that:

```
jison file.jison --case-insensitive
```

But nowhere in the documentation I could find it. Does it exist?

Thanks

**Comment by humberts90** [comment]
Gracias/thanks!

**Comment by 201318666** [comment]
thank you
